EMCECS/charts

ecs-cluster/svc-configs/blob/blobsvc-log4j2.xml, ecs-cluster/svc-configs/cm/cm-log4j2.xml, ecs-cluster/svc-configs/event/eventsvc-log4j2.xml, ecs-cluster/svc-configs/metering/metering-log4j2.xml, ecs-cluster/svc-configs/objectsvc/objectsvc-log4j2.xml, ecs-cluster/svc-configs/resource/resourcesvc-log4j2.xml, ecs-cluster/svc-configs/rm/rm-log4j2.xml, ecs-cluster/svc-configs/sm/storagemanagementsvc-log4j2.xml, ecs-cluster/svc-configs/sr/sr-log4j2.xml, ecs-cluster/svc-configs/ssm/ssm-log4j2.xml
[OBSDEF-4604](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-4604)
update log4j files for ecs dt services. 
=> [OBSDEF-4604] update log4j config

objectscale-manager/templates/operator-rbac.yaml
- Fix Operator RBAC for storagepools since it's cluster level resource
Charts custom CI №37
=> [OBSDEF-4332] Fix Operator RBAC for storagepools

Makefile, tools/alert-report/alert_reporter.py, tools/issues_events_report/issues_events_reporter.py
Generates this table https://confluence.cec.lab.emc.com/display/OBJSCALE/Autogenerated+ObjectScale+Alerts
=> [MONITORING-1004] Tools for Alert report auto-generation

objectscale-manager/templates/operator-rbac.yaml
- Add full permissions for VMware resources
=> [OBSDEF-4332] Add full permissions for VMware resources

ecs-cluster/templates/ecs-cluster.yaml, ecs-cluster/values.yaml
=> add pravega options

ecs-cluster/templates/ecs-cluster.yaml, ecs-cluster/values.yaml
OBSDEF-5214
Add collocated flag
=> [OBSDEF-5214] Add collocated flag

ecs-cluster/templates/ecs-cluster.yaml, ecs-cluster/values.yaml
[OBSDEF-5013](https://jira.cec.lab.emc.com/browse/OBSDEF-5013)
add rr-driven related feature flags
=> [OBSDEF-5013] add rr-driven related feature flags

ecs-cluster/alerts/issues/4020_OBJECTSTORE_MONITORING_FLUXD_issue.yaml, ecs-cluster/alerts/remedies/4020_OBJECTSTORE_MONITORING_FLUXD_remedies.yaml
[MONITORING-889](https://asdjira.isus.emc.com:8443/browse/MONITORING-889)
Related JIRA: https://eos2git.cec.lab.emc.com/ECS/monitoring/pull/463
=> [MONITORING-889] add fluxd alert

objectscale-vsphere/templates/vsphere-plugin-configmap.yaml, objectscale-vsphere/values.yaml
[OBSDEF-5457](https://jira.cec.lab.emc.com/browse/OBSDEF-5457)
Added Beta3 Feature Flags and mechanism to vpshere plugin's configmap
=> Feature obsdef 5457 add feature flag mechanism

ecs-cluster/values.yaml
[OBSDEF-5013](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5013)
enable feature rr-driven by default
https://asd-ecs-jenkins.isus.emc.com/jenkins/job/ecs-flex-automation-custom-runner/2553/
=> [OBSDEF-5013] enable feature rr-driven by default.

objectscale-manager/templates/operator.yaml
[OBSDEF-5283](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5283)
Add dcm service name to operator env
=> [OBSDEF-5283] expose dcm service hostname to ecs-cluster services

supportassist/values.yaml
[OBSDEF-5714](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5714)
- new ESE 2.2.0
```
uid: 33b45516-adbe-4c31-a3e8-a25c70881ef9
spec:
cloudIQ:
capacity: 0
enabled: false
health: 0
inventory: 0
performance: 0
usageIntelligence: 0
enabled: true
eventMuted: true
gateways: null
productModel: OBJECTSCALE
productName: OBJECTSCALE
productType: dell.enterprise.storage.objectscale
productVersion: 0.66.0
remoteAccessEnabled: false
siteID: 11145366
systemMode: preProd
testDialHome: true
useGateways: false
status:
keyPINHash: $2a$10$9HSCAx4Qb0aehW5Z8p062uevn9pYA4jHsEmnIUwK90zDqlDr9Mtzu
lastConnected: "2021-02-08T04:25:10Z"
lastUpdated: "2021-02-08T04:25:10Z"
remoteAccessIP: ""
serialNumber: ELMOBJ0221DNHX
state: Connected
statusMessage: 'SupportAssist is Connected with Serial Number : …
```
=> OBSDEF-5714 - new ESE version 2.2.0.0

objectscale-iam/README.md
[OBSDEF-5606](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5606)
Changing the README to reflect setting name change
=> [OBSDEF-5606] update README with name changes for drop66

ecs-cluster/templates/ecs-cluster.yaml, ecs-cluster/values.yaml
- Add feature flag for new provision API
=> [OBSDEF-1778] Add feature flag for new provision API

helm-controller/templates/deployment.yaml
Tested with make build, make package.
=> [OBSDEF-5343] Option to specify install-controller startup command for test purposes

objectscale-graphql/templates/graphql-deployment.yaml, objectscale-manager/templates/healthcheck-rbac.yaml, objectscale-manager/templates/objectscale-manager-app-configmap.yaml
[OBSDEF-5672](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5672)
Add RBAC for ObjectScale Healthcheck & fix rest endpoint
=> [OBSDEF-5672] Add RBAC for ObjectScale Healthcheck & fix rest endpoint

Makefile, vmware/vmware_pack.sh
This change detects the operating system via uname, and modify the sed command flags to match.
[OBSDEF-4031](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-4031)
=> [OBSDEF-4031] Add support for Darwin (MacOS) clients in “make package”

objectscale-graphql/templates/objectscale-admin-cluster-role.yaml, objectscale-graphql/templates/objectscale-admin-role.yaml
[OBSDEF-6249](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6249)
Add resourcequota to clusterrole to query across namespaces
=> [OBSDEF-6249] Add resourcequota to clusterrole to query across namespaces

ecs-cluster/alerts/issues/12001_12002_UNREAD_BYTES_DURING_PAUSE_issue.yaml, ecs-cluster/alerts/issues/12003_REPLICATION_STREAM_SEALED_issue.yaml
Add alert definition for geoservice pipeline.
=> [OBSDEF-3069] add alerts for geoservice pipeline

ecs-cluster/alerts/issues/1700_1701_PRAVEGA_CONNECT_issue.yaml, ecs-cluster/alerts/remedies/1700_1701_PRAVEGA_CONNECT_remedies.yaml
[OBSDEF-6940]https://jira.cec.lab.emc.com/browse/OBSDEF-6940
Add pravega connect failed config
=> add pravega connect alert config

supportassist/values.yaml
[OBSDEF-7226](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7226)
- Remove hardwired version of ESE
```
helm install objs-sa ./supportassist --set product=objectscale,productVersion=0.71.2,siteID=11145366,pin=5555,gateways[0].hostname="10.249.238.250",gateways[0].port=9443,gateways[0].priority=20 --set accessKey=A05C5BFF --set global.registry=asdrepo.isus.emc.com:9042 --set image.tag=latest --set tag=2.71.0-195.53793a9
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/epavkovi/kube/config.kind
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/epavkovi/kube/config.kind
NAME: objs-sa
LAST DEPLOYED: Tue Apr 13 15:32:23 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you …
```
=> OBSDEF-7226 - now use master build of dell-supportassist-ese, no longer hardwire version

objectscale-portal/values.yaml
[OBSDEF-7310](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7310)
- Enabled IAM/Accounts Feature UI 
- Enabled Buckets(v2) Feature UI
- Added new feature flag for New/Edit ObjectStore workflows 
=> [obsdef-7310] - Added feature flag for Object store workflow and enabled buckets, iam on objectscale-portal

objectscale-manager/Chart.yaml
[OBSDEF-7023](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
- Fix charts.yaml
=> [OBSDEF-7023] fix charts

ecs-cluster/tests/initial_user_secret_test.yaml
=> [OBSDEF-7475] deprecate ecs cluster provision tests

ecs-cluster/values.yaml
[OBSDEF-7353](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7353)
Added placeholder for GeoReceiver network connection external parameters config
=> OBSDEF-7353 GeoReceiver network connection - external params placeholder

ecs-cluster/templates/ecs-cluster.yaml, ecs-cluster/templates/pravega-rbac.yaml
[OBSDEF-6964](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6964)
Add pravega service account with imgPullSecret and set it to bk and prvg service account parameter
The tests in our environment have passed, both positive and negative cases.
=> [OBSDEF-6964]Add pravega service account with imgPullSecret and set it to bk and prvg sa parameter

ecs-cluster/templates/ecs-cluster.yaml, ecs-cluster/values.yaml
- Add enable ephemeral storage flag
=> Add enable ephemeral storage flag

ecs-cluster/alerts/issues/12004_TARGET_BUCKET_QUOTA_EXCEEDED_issue.yaml, ecs-cluster/alerts/issues/12005_TARGET_OBJECTSTORE_FULL_issue.yaml
[OBSDEF-6313]
Add alert definition of destination bucket quota exceeded and object store full for CRR.
=> [OBSDEF-6313] add objectstore and bucket quota

Makefile
=> [OBSDEF-7566] Makefile options needed to generate pre-release

objectscale-manager/values.yaml, supportassist/values.yaml, tools/build_helper/version_resolver.py
=> [OBSDEF-7566] Comment rfw update markers for certain image tags that are not available in 0.72

ecs-cluster/templates/objectstore-app-configmap.yaml, ecs-cluster/values.yaml
Add a post upgrade healthcheck to get a final status after upgrade
operations.
[OBSDEF-7442](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7442)
=> [OBSDEF-7442] Add post upgrdae healthcheck

ecs-cluster/templates/ecs-cluster.yaml, ecs-cluster/values.yaml
[OBSDEF-885](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-885)
Added tls section in chart for operator to pick up for generate CA for georeceiver.
=> [OBSDEF-885] tls configuration for georeceiver

objectscale-graphql/templates/graphql-deployment.yaml
=> [OBSDEF-8130] adding env for platform type to graphql

ecs-cluster/svc-configs/storageserver/storageserver.conf, ecs-cluster/templates/objectstore-rbac.yaml
* config directs storageserver to get disk information via Fabric Agent REST API
* storageserver pod gets right to watch pvcs
=> [OBSDEF-5967] Configure storagserver to get disk information dynamically via Fabric Agent REST API

ecs-cluster/svc-configs/geoservice/geoservice-log4j2.xml
[OBSDEF-6122](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6122)
=> [OBSDEF-6122] change geoservice log level

ecs-cluster/alerts/issues/12001_UNREAD_BYTES_DURING_PAUSE_issue.yaml, ecs-cluster/alerts/issues/12006_REPLICATION_CERTIFICATE_ERROR.yaml
[OBSDEF-3644](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-3644)
=> [OBSDEF-3644] add alert for CRR tls

ecs-cluster/values.yaml
[OBSDEF-8618](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
For CRR, bring up geo service by default 
=> [OBSDEF-8618] For CRR, enable geo service by default

ecs-cluster/svc-configs/ons/ons-log4j2.xml
[OBSDEF-8626](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8626)
- Enable DirectAggregator debug logs for event writes
- Disable noisy logs DynamicConfigNode and DataNodeAddressCache
=> [OBSDEF-8626] ONS enable aggregator debug logs and filter noisy logs

objectscale-manager/values.yaml
=> turned on all the cloudIQ reports

objectscale-manager/alerts/issues/OBJSOP-1000_DISK_REPLACEMENT_issue.yaml, objectscale-manager/alerts/issues/OBJSOP-1001_PMM_issue.yaml, objectscale-manager/alerts/issues/OBJSOP-1002_TMM_issue.yaml, objectscale-manager/alerts/issues/OBJSOP-1003_UPGRADE_issue.yaml, objectscale-manager/alerts/issues/OBJSOP-1004_EXPAND_issue.yaml, objectscale-manager/alerts/remedies/OBJSC-SP-0003_TMM_remedies.yaml, objectscale-manager/alerts/remedies/OBJSOP-1000_DISK_REPLACEMENT_remedies.yaml, objectscale-manager/alerts/remedies/OBJSOP-1001_PMM_remedies.yaml, objectscale-manager/alerts/remedies/OBJSOP-1002_TMM_remedies.yaml, objectscale-manager/alerts/remedies/OBJSOP-1003_UPGRADE_remedies.yaml, objectscale-manager/alerts/remedies/OBJSOP-1004_EXPAND_remedies.yaml, objectscale-manager/values.yaml
[OBSDEF-5464](https://jira.cec.lab.emc.com/browse/OBSDEF-5464)
Added issues and remedies for KAHM events sent during managing following Service Procedures:
- Disk Replacement
- Permanent Maintenance Mode
- Temporary Maintenance Mode
- Upgrade
- Horizontal SS Expand
=> [OBSDEF-5464] Add KAHM event rules for Operator events

ecs-cluster/templates/ecs-cluster.yaml, ecs-cluster/templates/svc_common_vars.yaml
[OBSDEF-4084](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-4084)
Add logging labels and SP labels.
=> [OBSDEF-4084]add SP and logging labels for Zookeeper

decks/templates/decks.yaml, decks/values.yaml
environment variables to pass polling interval and age of the  file to delete
[OBSDEF-1877](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-1877)
environment variables to pass polling interval and age of the  file to delete
=> [OBSDEF-1877]  garbage collector configuration

kahm/values.yaml
[OBSDEF-6881](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6881)
Need to pick-up the testapp image tag from the automation.
=> [OBSDEF-6881] testapp image tag

objectscale-manager/templates/operator-rbac.yaml
https://jira.cec.lab.emc.com/browse/OBSDEF-8967
https://asd-ecs-jenkins.isus.emc.com/jenkins/job/charts-custom-ci/158/
=> [OBSDEF-8967] Operator: add ability to list/get volumes.csi-baremetal.dell.com

atlas-operator/templates/role.yaml
[OBSDEF-9024](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9024)
Add PDB actions to roles.yaml
<pre><font color="#3465A4">[</font><font color="#CC0000">root@flexdevkit:~</font><font color="#3465A4">]</font><font color="#4E9A06">$ </font><font color="#D3D7CF"><b>kubectl get pods | grep atlas</b></font>
<font color="#D3D7CF"><b>atlas-operator-c8d96584c-8qgcz                            1/1     Running             0          2m59s</b></font>
<font color="#D3D7CF"><b>federation-atlas-0                                        1/1     Running             0          2m38s</b></font>
<font color="#D3D7CF"><b>objectscale-dcm-atlas-0                                   1/1     Running             0          2m39s</b></font> …
=> [OBSDEF-9024] PDB permissions

objectscale-manager/values.yaml
https://jira.cec.lab.emc.com/browse/OBSDEF-8978
=> [OBSDEF-8978] Change Openshift to OpenShift in valid values list

.gitignore, decks/templates/decks-app-configmap.yaml, decks/templates/healthchecks-rbac.yaml, decks/values.yaml
=> [OBSDEF-9022] Add DECKS Preupdate Healthcheck

kahm/templates/healthchecks-rbac.yaml, kahm/templates/kahm-app-configmap.yaml, kahm/values.yaml
=> [OBSDEF-9031] Add KAHM preupdate healthcheck

objectscale-manager/values.yaml
=> Enable SP operator by default

objectscale-manager/templates/operator-rbac.yaml
Operator is needed to read CSI resources (such as Volumes, ACs)
Operaotor is needed to update CSI resources. E.g. add annotations
=> [OBSDEF-9009] Integrate Operator with Baremetal CSI for DR

atlas-operator/templates/_helpers.tpl, atlas-operator/templates/deployment.yaml, ecs-cluster/templates/ecs-cluster.yaml, federation/templates/atlas_v1beta1_fedcluster.yaml, objectscale-dcm/templates/atlas_v1beta1_dcmcluster.yaml, objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
[OBSDEF-8599](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8599)
Add component labels
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/197/
<pre><font color="#3465A4">[</font><font color="#CC0000">root@flexdevkit:~</font><font color="#3465A4">]</font><font color="#4E9A06">$ </font><font color="#D3D7CF"><b>grep -B 4 &quot;component: atlas&quot; /tmp/yaml </b></font>
<font color="#D3D7CF"><b>      appplatform.vmware.com/vsphere-emm-integrated: &quot;true&quot;</b></font>
<font color="#D3D7CF"><b>    creationTimestamp: &quot;2021-06-15T23:49:05Z&quot;</b></font>
<font color="#D3D7CF"><b>    generateName: atlas-operator-6f6f6d955b-</b></font> …
=> [OBSDEF-8599] atlas and atlas-operator component lables

atlas-operator/values.yaml, objectscale-dcm/templates/atlas_v1beta1_dcmcluster.yaml, objectscale-dcm/templates/deployment.yaml, objectscale-dcm/values.yaml
[OBSDEF-8755](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8755)
[OBSDEF-9389](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9389)
Set memory requests and limits for DCM, DCM-Atlas, Atlas-Operator
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/213/
<pre><font color="#3465A4">[</font><font color="#CC0000">root@flexdevkit:~</font><font color="#3465A4">]</font><font color="#4E9A06">$ </font><font color="#D3D7CF"><b>kubectl get pods</b></font>
<font color="#D3D7CF"><b>NAME                                               READY   STATUS    RESTARTS   AGE</b></font>
<font color="#D3D7CF"><b>atlas-operator-7cd46bf6fd-tsg56                    1/1 …
=> [OBSDEF-9389] [OBSDEF-8755] memory requests and limits for atlas and dcm

objectscale-manager/templates/objectscale-manager-app-configmap.yaml, objectscale-manager/values.yaml, objectscale-vsphere/templates/skyline-health-configmap.yaml
Add the catalog config map for skyline health
[OBSDEF-1996](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-1996)
=> [OBSDEF-1996] Add configmap for skyline health

Dockerfile, docs/index.yaml, helm-controller/values.yaml
- to support vsphere updates needed latest install-controller
- to match da charts
[OBSDEF-9915](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
in progresso
=> [OBSDEF-9915]- build and pull in latest install-controller

kahm/templates/kahm.yaml
=> [OBSDEF-9636] Add label to find kahm easier

decks/templates/decks-app-configmap.yaml
Missing tabs are added to pass PR validation
https://asd-ecs-jenkins.isus.emc.com/jenkins/job/charts-custom-ci/253/
=> [OBSDEF-7152] add missing tabs

README.md
https://jira.cec.lab.emc.com/browse/OBSDEF-9795
Small readme update after migration
Charts-bin readme update PR:
https://github.com/EMCECS/charts-bin/pull/4
N/R
=> [OBSDEF-9795] update readme

Makefile, snmp-notifier/Chart.yaml, snmp-notifier/values.yaml
https://jira.cec.lab.emc.com/browse/OBSDEF-9988
=> [OBSDEF-9988] Add snmp-notifier to DECKSCHARTS and fix x.76.0 versions
