EMCECS/charts

- objectscale-manager/templates/operator-rbac.yaml
-  Fix Operator RBAC for getting storagepools of PSP
- Storagepools is cluster-level so Operator needs to use `ClusterRole`
> [OBSDEF-4332] Fix Operator RBAC for storagepools

- ecs-cluster/values.yaml
- On slow clusters, we may encounter unwanted triggering
> [OBSDEF-4751] Fix progress deadline seconds

- supportassist/templates/supportassist.yaml
[OBSDEF-4865](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-4865)
- Remove LoadBalancer from supportassist k8s service
```
helm install sa ./supportassist --set product=objectscale,productVersion=0.64.0,siteID=11145366,pin=5555,gateways[0].hostname="10.1.1.1",gateways[0].port=9443,gateways[0].priority=20 --set global.registry=asdrepo.isus.emc.com:9042 --set accessKey=6F27BE20
└─ $ ▶  kubectl get svc
NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
decks-support-store                      ClusterIP   10.96.168.25    <none>        7443/TCP            5m36s
kahm-headless                            ClusterIP   None            <none>        60000/TCP           5m52s
kahm-restapi                             ClusterIP   10.96.183.122 …
```
> OBSDEF-4865 - remove LoadBalancer service setting for ESE pod/svc

- ecs-cluster/templates/healthcheck-rbac.yaml
- ecs-cluster/templates/objectstore-app-configmap.yaml
The health checks run may need to list things like ecsclusters to figure out
if the state of the component is healthy (in objectstore-pre-update check's
case). Use a new job-runner service account for this which lets us fine tune
RBAC for health checks without overloading existing serviceaccounts. This
does not use the KAHM service account because job-runner covers only its
specific namespace, while kahm might have access to other namespaces.
https://jira.cec.lab.emc.com/browse/OBSDEF-4831
> [OBSDEF-4831] Fix healthcheck RBAC

- decks/Chart.yaml
- decks/values.yaml
- dellemc-license/Chart.yaml
- dellemc-license/values.yaml
- dks-testapp/Chart.yaml
- dks-testapp/values.yaml
- docs/index.yaml
- kahm/Chart.yaml
- kahm/values.yaml
- service-pod/Chart.yaml
- service-pod/values.yaml
- srs-gateway/Chart.yaml
- srs-gateway/values.yaml
[ATL-1455](https://jira.cec.lab.emc.com:8443/browse/ATL-1455)
- set version to 1.2.5
tbd once images have been created.
> ATL-1455 - set version of decks/kahm to 1.2.5 for SDP

- ecs-cluster/svc-configs/rep/repsvc-log4j2.xml
- ecs-cluster/templates/svc-configs.yaml
- ecs-cluster/tests/svc_log4j2_test.yaml
- ecs-cluster/values.yaml
[OBSDEF-4989](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-4989)
This PR adds a log4j ConfigMap for the `rep` service with a copy of its log4j2 config file.
Another ConfigMap for repsvc-specific configuration is added.  This second ConfigMap is populated by a helm value (empty by default but settable with a `--values` file) and will be mounted into the service pod.  It could contain any service-specific configuration but repsvc needs it to allow injecting a Java properties files to allow configuration settings without having to rebuild images.
The corresponding flex-operator changes are in this PR: https://eos2git.cec.lab.emc.com/ECS/ecs-flex-operator/pull/282
- **Build** - https://asd-ecs-jenkins.isus.emc.com/jenkins/job/operator-custom-build/438/
- **Test run** - …
> [OBSDEF-4989] ConfigMaps for repsvc

- supportassist/values.yaml
[OBSDEF-5177](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5177)
- Set ESE image tag to 2.1.1.55
- Yes this is static because we only change this once every 2 months.
Ran helm install of newly build 2.1.1.55 image,  testing worked great standalone and w decks
> OBSDEF-5177 - change ese image tag to 2.1.1.55

- dellemc-license/templates/dellemc-license-app-configmap.yaml
[OBSDEF-5008](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5008)
- Remove autoclear timeout 
- Add DECKS-LIC-1002 normal event to clear the expiring licensing issue.
```
└─ $ ▶  helm upgrade objs-lic ./dellemc-license --reuse-values --set product=objectscale
└─ $ ▶  kubectl get cm dellemc-objectscale-license-app-config  -o yaml
apiVersion: v1
data:
eventRemedies: |-
symptoms:
- symptomid: DECKS-LIC-1005
description: Dell EMC subscription license expired for product objectscale
remedies:
- Check the end date of the objectscale license
- Visit the Dell EMC Software Licensing Center (SLC) to
renew/extend the objectscale license.
- Contact your Dell EMC sales representative to
renew/extend the objectscale license
- symptomid: DECKS-LIC-1006
description: Dell EMC subscription license for …
```
> [OBSDEF-5008] - remove autoclear timeout, add event to clear issue

- ecs-cluster/templates/svc-configs.yaml
- ecs-cluster/tests/svc_log4j2_test.yaml
- ecs-cluster/values.yaml
[OBSDEF-3902](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-3902)
[OBSDEF-5270](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5270)
This PR adds service-specific ConfigMaps for objectsvc and resourcesvc to allow setting properties through injected property files.
Related PR for the flex-operator: https://eos2git.cec.lab.emc.com/ECS/ecs-flex-operator/pull/287
Test run with corresponding flex-operator change: https://asd-ecs-jenkins.isus.emc.com/jenkins/job/ecs-flex-automation-custom-runner/2453/
> [OBSDEF-3902, OBSDEF-5270] Add ConfigMaps for resourcesvc and objectsvc

- Makefile
- objectscale-graphql/values.yaml
[OBSDEF-5349](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5349)
- Added new "graphqlver" make targe to automate setting objectstore and decks charts for graphql
- This new target will be called during `make release`
- eliminates having to hand-edit values.yaml for release builds
- Fixed up yqcheck to use Makefile `ifneq` statements
- Added extra # comments in `objectscale-graphql/values.yaml` is because `yq` removes blank lines.
```
└─ $ ▶  make graphqlver PACKAGE_VERSION=0.66
yq e '(.objectStoreAvailableVersions[0] = "0.66.0") | (.decks.licenseChartVersion = "2.0.66") | (.decks.supportAssistChartVersion = "2.0.66") ' -i objectscale-graphql/values.yaml
sed -i '1s/^/---\n/' objectscale-graphql/values.yaml
yamllint -c .yamllint.yml objectscale-graphql/values.yaml
epavkovi @ ubuntu …
```
> OBSDEF-5349 - Automate setting versions in graphql values charts

- influxdb-operator/templates/role.yaml
- statefuldaemonset-operator/templates/role.yaml
[MONITORING-1064](https://asdjira.isus.emc.com:8443/browse/MONITORING-1064)
[MONITORING-1065](https://asdjira.isus.emc.com:8443/browse/MONITORING-1065)
Added permissions for statefuldaemonset and influxdb operators to fix deployment of rsyslog and InfluxDB on Openshift.
vsphere: https://asd-ecs-jenkins.isus.emc.com/jenkins/job/ecs-flex-automation-custom-runner/2506/
atlantic: https://asd-ecs-jenkins.isus.emc.com/jenkins/job/ecs-flex-automation-custom-runner/2499/robot/report/log.html
> [MONITORING-1064][MONITORING-1065] Fixed permissions for rsyslog and influxdb operators

- objectscale-manager/templates/objectscale-manager-app-configmap.yaml
[OBSDEF-5672](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5672)
The indention was incorrect on the health check configuration of the objectscale-manager application configuration configmap for KAHM.
> [OBSDEF-5672] Fix incorrect indention in configmap

- Makefile
- ecs-cluster/templates/ecs-cluster.yaml
- objectscale-vsphere/templates/vsphere-plugin-deployment.yaml
- objectscale-vsphere/templates/vsphere-plugin-secrets.yaml
- vmware/vmware_pack.sh
[OBSDEF-5766](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5766)
Add dark site feature for 0.64.x
All pods start correctly, currently running into an issue where the namespace does not populate under vsphere UI for objectstore creation.
> [OBSDEF-5766] - Allow docker registry and credentials to be set for ObjectScale on vSphere7

- ecs-cluster/templates/objectstore-app-configmap.yaml
- helm-controller/templates/service.yaml
- objectscale-graphql/templates/graphql-deployment.yaml
[OBSDEF-5672](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5672)
This change is needed to support one-click install procedures, in which the GraphQL service will retrieve Helm chart information from the installer via REST
> [OBSDEF-5672] Add Installer REST credentials to GraphQL deployment

- dellemc-license/templates/dellemc-license-app-configmap.yaml
- dellemc-license/templates/dellemc-license-app.yaml
[OBSDEF-5726](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5726)
- Changed app managed-by field to be managed by service it was installed by
- 
```
└─ $ ▶  helm install objs-lic ~/src/emcecs/charts/dellemc-license --set-file licensefile=/home/epavkovi/vmshare/OBJS_Echo_Cloud_Perf_20210201.xml --set product=objectscale
NAME: objs-lic
LAST DEPLOYED: Thu Feb 18 22:53:34 2021
NAMESPACE: dellemc-objectscale-domain-c54
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing dellemc-license. This release is capable of
deploying a Dell EMC license secret to create Dell EMC k8s license resource.
Your release is named objs-lic.
To install dellemc-license by using Helm chart, use the helm install command below:
$ helm install <repository name>/dellemc-license --set-file …
```
> OBSDEF-5726 - Change dellemc-license managed-by in app resource so that managed by correct service

- ecs-cluster/templates/ecs-cluster.yaml
- ecs-cluster/values.yaml
[OBSDEF-1200](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-1200)
add support of bk blockOwnerDeletion parameter
> [OBSDEF-1200]add support of bk blockOwnerDeletion parameter

- supportassist/templates/supportassist-cr.yaml
[OBSDEF-5307](https://jira.cec.lab.emc.com/browse/OBSDEF-5307)
When we are using direct mode(useGateways=false), we need to set remoteAccessEnabled=false.
support assist cr:
```
...
remoteAccessEnabled: true
siteID: 11145366
systemMode: preProd
testDialHome: true
useGateways: true
...
```
Run `helm upgrade sa supportassist/ --reuse-values --set useGateways=false`
Now support assist cr:
```
...
remoteAccessEnabled: false
siteID: 11145366
systemMode: preProd
testDialHome: true
useGateways: false
...
```
> [OBSDEF-5307] - Set remote access enabled to false if using direct mode

- ecs-cluster/templates/objectstore-app-configmap.yaml
- objectscale-manager/templates/objectscale-manager-app-configmap.yaml
The pre-update health checks should not run on a timer, they should be
run before a user is allowed to upgrade. The checks always require a
-target-version to be passed in to validate the upgrades is allowed.
> [OBSDEF-6241] Remove schedule for pre-update check

- Makefile
- decks/templates/decks.yaml
- decks/values.yaml
- service-pod/templates/deployment.yaml
- service-pod/values.yaml
[NPS-8152] sshd in service-pod on openshift requires SYS_CHROOT capability
https://asdjira.isus.emc.com:8443/browse/NPS-8152
sshd is failing to chroot into /run/sshd, as a result it failing to accept ssh connection.
Since openshift 4.5.16 capability SYS_CHROOT was dropped from defaults, it needs to be explicitly mentioned in capabilities.
https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html
On openshift:
with deck-install values
```
service-pod:
podSecurityContext:
enabled: true
```
service-pod-service-pod           LoadBalancer   172.30.251.63    10.243.58.35   22:30766/TCP                 30s
```
ssh root@10.243.58.35
root@10.243.58.35's password: 
* Welcome to the Dell EMC …
```
> NPS-8152 sshd in service-pod on openshift requires SYS_CHROOT capability

- ecs-cluster/templates/NOTES.txt
[OBSDEF-6327](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6327)
```
ben@ben:~/workspace/charts$ make test
helm lint ecs-cluster objectscale-manager mongoose zookeeper-operator atlas-operator decks kahm dks-testapp fio-test sonobuoy dellemc-license service-pod helm-controller objectscale-graphql objectscale-vsphere objectscale-portal objectscale-iam pravega-operator bookkeeper-operator supportassist decks-support-store statefuldaemonset-operator influxdb-operator federation logging-injector dcm --set product=objectscale --set global.product=objectscale
engine.go:159: [INFO] Missing required value: target.accessKey is required
engine.go:159: [INFO] Missing required value: .target.secretKey is required
engine.go:159: [INFO] Missing required value: …
```
> [OBSDEF-6327] Updating notes to use IAM credentials

- ecs-cluster/templates/objectstore-app-configmap.yaml
- objectscale-manager/templates/objectscale-manager-app-configmap.yaml
- objectscale-manager/values.yaml
The pre-upgrade checks need a `-target-version` argument to know which
version a user is attempting to upgrade to. In the health check screen,
there is no option to choose a version, only a health check to run.
Default to using the current version so that the check can still run
successfully when called without arguments.
[OBSDEF-6350](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6350)
> [OBSDEF-6350] Add default args for pre-upgrades

- decks/templates/test/test-app.yaml
- decks/templates/testapp-rbac.yaml
- dks-testapp/templates/app-configmap.yaml
- dks-testapp/templates/event-configmap.yaml
- dks-testapp/templates/test/test-app.yaml
- dks-testapp/values.yaml
[OBSDEF-5227](https://jira.cec.lab.emc.com/browse/OBSDEF-5227)
changes in dks-testapp chart to remove srs test
helm test decks pod logs:
```
Error during unmarshalling custom config open /etc/config/logger-config.yaml: no such file or directory. Using default config
time="2021-03-11T08:27:57Z" level=info msg="Starting decks-testapp version: 2.0.68-185.4ff59cb" func="main.main() " file="main.go:58"
time="2021-03-11T08:27:58Z" level=info msg="DECKS POD is ready" func="main.main() " file="main.go:101"
time="2021-03-11T08:27:58Z" level=debug msg="orig name: dellemc-unisphere-license sanitized name: dellemc-unisphere-license" func="secrets.sanitize() " file="secrets_controller.go:509"
time="2021-03-11T08:27:58Z" level=info msg="test-unisphere-lic secret is created, kubectl output: …
```
> [OBSDEF-5227] - Remove srs test in dkstestapp and add support assist test in decks testapp and dks testapp

- objectscale-graphql/Chart.yaml
- objectscale-portal/Chart.yaml
- objectscale-vsphere/Chart.yaml
Fixes following broken re-build process:
```
git clone https://github.com/EMCECS/charts.git
...
make build
Error: can't get a valid version for dependency helm-controller
Error: can't get a valid version for dependency objectscale-portal
```
if clear chart package caches (as done in automation):
```
rm */charts/*
make build   -> same errors
make build
make package
Error: found in Chart.yaml, but missing in charts/ directory: objectscale-portal
Makefile:219: recipe for target 'create-vsphere-templates' failed
make: *** [create-vsphere-templates] Error 1
```
> [OBSDEF-6337] Rebuild fix

- Makefile
- objectscale-manager/Chart.yaml
- objectscale-manager/values.yaml
- 6651 - enable dcm
- 6675 - use v1.16.10 for k8s-kubectl
- 193 - finally remove the helm repo check for make build
```
─ $ ▶  kubectl get pod
NAME                                                              READY   STATUS      RESTARTS   AGE
atlas-operator-5bc9d7c5bb-7v75s                                   1/1     Running     0          29m
decks-5c6cb98697-4rmcr                                            1/1     Running     0          25m
decks-support-store-0                                             1/1     Running     0          25m
dellemc-eddie-697-domain-c44-wcp-sp-patch-gzbxm                   0/1     Completed   0          29m
fedsvc-857d9f6958-dhrms                                           1/1     Running …
```
> [OBSDEF-6651] [OBSDEF-6775] [OBSDEF-193] - Charts update for build 70

- dcm/templates/deployment.yaml
- federation/templates/federation_deployment.yaml
- objectscale-iam/templates/deployment.yaml
[OBSDEF-6774](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6774)
- Updated iam, fed & dcm to standardize on global.registrySecret
- Built new charts and install-controller 
- Deployed on Andre all pods started:
> [OBSDEF-6774] - Use std global.registrySecret to set imagePullSecrets

- supportassist/templates/ese-callback-rbac.yaml
[OBSDEF-6572](https://jira.cec.lab.emc.com/browse/OBSDEF-6572)
change rbac for callback to log events
Send a callback api request with a transaction error:
```
bash-4.4# curl --request POST --url 10.96.91.70:9447/objectscale/data --header 'content-type: application/json' --header 'x-dell-auth-key: tmpKey4U' --data '{"payloadType":"callback","payloadVersion":"1.0","data":{"operation":"event","transaction-id":"12345","sent-transaction-id":"54321","status":"failed","message":"1, '\''True'\''"}}'
```
Callback pod log:
```
time="2021-03-19T08:37:00Z" level=debug msg="authKey is tmpKey4U" func="util.GetAuthKeyUsingGoClient() " file="ese_helper.go:164"
time="2021-03-19T08:37:00Z" level=debug msg=Entering func="api.RestService.ESEData() " file="callback.go:32"
time="2021-03-19T08:37:00Z" …
```
> [OBSDEF-6572] - Log a kahm event when getting transaction error in callback

- Makefile
- tools/build_helper/sort_charts_by_deps.py
Wrong order of initial CHARTS list leads to build issues, like using cached chart package of dependency in chart that requires newly rebuilt package.
Fix order of CHARTS in build time so that dependent charts are always built in the end.
Tested by running `make build`, verifying that sort script works as expected.
> [OBSDEF-6780] Sort CHARTS list by dependency order

- Makefile
- tools/build_helper/sort_charts_by_deps.py
This resolution differs from https://github.com/EMCECS/charts/pull/704 in following way:
When use specifies `make build CHARTS=....` then list of charts in CHARTS=... is considered as sub-set and forwarded to sorting script that sorts this sub-set and also adds all dependent charts in appropriate order.
For example, if user specified CHARTS=...., these charts will be re-build automatically:
```
input charts list          rebuilds
-----------------          --------
kahm                       kahm
dcm                        dcm, objectscale-manager
objectscale-graphql        objectscale-graphql, objectscale-portal, objectscale-vsphere
helm-controller            helm-controller, objectscale-graphql, objectscale-portal, objectscale-vsphere
```
> [OBSDEF-7139] Allow users to run make build with custom list of charts, improved version with sorting

- objectscale-manager/templates/operator.yaml
[OBSDEF-7081](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7081)
Added environment variable with federation servie name to resolve DNS name for REST requests in the operator.
```
kubectl exec objectscale-operator-5b8855dc58-9pjpp -- printenv | grep FEDERATION
FEDERATION_SERVICE_NAME=fedsvc
```
> [OBSDEF-7081] Add fed svc name env variable in the operator

- ecs-cluster/values.yaml
https://jira.cec.lab.emc.com/browse/OBSDEF-6936
set the objectstore metering svc to default enabled.
helm install objectstore ecs-cluster --set global.registry=asdrepo.isus.emc.com:8099 \
> --set performanceProfile=small \
> --set tag=$objTag \
> --set fabricProxy.image.tag=shippable \
> --set managementGateway.image.tag=shippable \
> --set zookeeper.image.tag=shippable \
> --set zookeeper.persistence.storageClassName=$otherStorage \
> --set managementGateway.service.type=LoadBalancer \
> --set syslogAgent.image.tag=$rsyslogTag \
> --set storageServer.replicas=$ssReplicas \
> --set s3.service.type=LoadBalancer \
> --set diagnostic.service.type=LoadBalancer \
> --set provision.enabled=True \
> --set storageServer.persistence.protected=False \
> --set …
> [OBSDEF-6936] set objectstore metering to default on

- ecs-cluster/values.yaml
[OBSDEF-3054](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-3054)
Add "http" prefix to georeciver CRR endpoint to be picked by operator to register to federation service
> [OBSDEF-3054] export georeceiver external endpoint

- tools/build_helper/version_resolver.py
Because build devkit uses Python 2
> [OBSDEF-7566] Make version_resolver.py compatible with Python 2

- objectscale-manager/templates/telemetry-rbac.yaml
- supportassist/templates/telemetry-rbac.yaml
[OBSDEF-7817](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7817)
Need to add namespace as a part of the cluster role and cluster role bindings for inventory charts as we need to create mukltiple objectscales across the namespaces.
- [x ] make test passed
- [x ] make build passed
> [OBSDEF-7817] - added namespace in the cluster role and cluster role bindings names

- influxdb-operator/values.yaml
- statefuldaemonset-operator/values.yaml
It turned that inserted monitoring tags break monitoring build/CI, and since their versions are inserted via global tag, it is better to skip their insertions.
> [OBSDEF-6862] Correction for monitoring image tags

- objectscale-portal/values.yaml
[OBSDEF-7310](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7310)
managerObjectStoreV2  Feature flag enabled by default,  The new Object store creation workflow will be enabled by default.
We have tried to enable this flag and see that the new Object Store UI Launches.
At Runtime, we tried to enabled/disable this flag to see if the old vs new UI Launches properly.
> Feature flag for managerObjectStoreV2 will be enabled by default

- objectscale-graphql/templates/objectscale-admin-cluster-role.yaml
[OBSDEF-5452](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5452)
Added an RBAC for GraphQL to be able to list and get AvailableCapacity CR
```
Charts:      28 passed, 28 total
Test Suites: 50 passed, 50 total
Tests:       240 passed, 240 total
Snapshot:    0 passed, 0 total
Time:        16.551611445s
```
> [OBSDEF-5452] adding RBAC for baremetal-csi resource access to graphql

- objectscale-portal/values.yaml
[OBSDEF-8300](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8300)
- back out the new objectstore v2 wizard.  not working well in build 73.
- Put the flag to false.  Orig wizard came up fine and we're able to create an objectstore
> [OBSDEF-8300] - back out new objectstore v2 changes not working

- ecs-cluster/svc-configs/bk-sp/bk-sp.sh
- objectscale-manager/templates/operator-rbac.yaml
[OBSDEF-7991](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7991)
Fix BK recovery script and allow sp operator to create pod/exec object
Tested on the cluster with the Disk Replacement SP. Recovery is a part of the 'first phase' and it passed.
SP operator log
```
2021-05-14T13:38:43.038Z	INFO	diskreplacement/diskreplacement.go:28	Executing Disk replacement Service Procedure
2021-05-14T14:05:25.685Z	INFO	diskreplacement/diskreplacement.go:28	Executing Disk replacement Service Procedure
2021-05-14T14:05:25.686Z	INFO	diskreplacement/diskreplacement.go:42	Processing 1st phase of DR for PVC index-ecs-cluster-bk-bookie-0
2021-05-14T14:06:34.520Z	INFO	diskreplacement/diskreplacement.go:28	Executing Disk replacement Service Procedure
2021-05-14T14:06:34.522Z	INFO …
```
> [OBSDEF-7991] Fix SP operator script exexcution 

- vmware/vmware_pack.sh
[OBSDEF-8341](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8341)
vmware/vmware_pack.sh was changed to create empty crd in configmap if service_id is not equal to "objectscale" (not default).
This is needed to skip crd removal when service is disabled.
Tested both manually and automatically. 
Automation change for skip patch verification if CRD were not installed by plugin was merged.
- [v] make test passed
- [v] make build passed
- [v] helm install <chart> passed
- [v] vSphere7 make package deployments passed
- [_] helm upgrade <chart> passed (not affected)
- [v] helm test <release_name> passed
https://asd-ecs-jenkins.isus.emc.com/jenkins/job/charts-ci-vsph7-large/513/robot/report/log.html
> [OBSDEF-8341] Install CRD prior to enabling supervisor service on vSphere

- ecs-cluster/values.yaml
[OBSDEF-3644](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-3644)
Change georeceiver port to https
> [OBSDEF-3644] tls integration for geo

- ecs-cluster/values.yaml
[OBSDEF-6288] Remove RFW tag from provision image since it is not used anymore
- [y] make test passed
- [y] make build passed
- [y] helm install <chart> passed
> [OBSDEF-6288] Remove RFW tag from provision image since it is not used anymore

- objectscale-manager/crds/ecscluster.yaml
[OBSDEF-7064](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7064)
1. Add name length validation using `openAPIV3Schema`
- [ 1] make test passed
- [ 1] helm install <chart> passed
1. Positive case with 27 characters
```
CLUSTER_RELEASE=${ECS_RELEASE:-ecs-cluster-with-a-very-lon}
[root@charlie:~]$ kubectl get pod
NAME                                                              READY   STATUS    RESTARTS   AGE
atlas-operator-76c655fd79-mbd4j                                   1/1     Running   0          2d16h
ecs-cluster-with-a-very-lon-management-gateway-5b6756d9b7-cnqh6   1/1     Running   0          2d16h
```
```
[root@charlie:~]$ curl $(kubectl get svc |grep "9101" | awk '{print $3":9101/stats/dt/DTInitStat/"}' ) | xmllint -format -
% Total    % Received % Xferd  Average Speed   Time …
```
> OBSDEF-7064 Add validation for ECS Cluster

- kahm/values.yaml
[OBSDEF-8703](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8703)
to spread the postgresql instances across the nodes
This will insure that the pods are spread across the nodes.
- [ x] make test passed
- [x ] helm install <chart> passed
- [ x] vSphere7 make package deployments passed
> [OBSDEF-8703]add anti-affinity rules 

- Makefile
- decks/decks-custom-values.yaml
- decks/templates/decks-app.yaml
- [] helm test <release_name> passed
Tested **both** helm install and application only install (letting install controller do the install)
```
decks-889f76cbd-86q6w                                             1/1     Running     0          19s
decks-support-store-84f8455b44-565ff                              1/1     Running     0          20s
```
both come up and the PVC for support store binds correctly.
**note** that the weird double copy/rm/transformation are because Helm is painful to convince to make templates. If the template file is in /templates (which is must be in) then it *has* to have a Kind and Version for `helm install ..` to work, but we do not have a kind for the custom values they are just an ease-of-use .values file, and …
> [OBSDEF-8955] Add DECKS upgrade support & custom settings

- Makefile
- kahm/kahm-custom-values.yaml
- kahm/templates/custom.yaml
- kahm/templates/kahm-app.yaml
Currently we build the chart values annotation by transforming the
*entire* .Values file into json, which outputs all settings including
ones that we do not pass in. This makes it impossible to pick out
specific settings and only propagate those during an upgrade.
The default values should be enough to bring up a component, and we only
need to keep track of a small subset that must be kept over an upgrade.
Doing the install this way lets us upgrade KAHM by only changing the
main chart-version annotation, and the rest of the subcharts and values
will be automatically updated from the new chart version.
[OBSDEF-3870](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-3870)
Applying the yaml file brings up kahm, updating the chart version …
> [OBSDEF-3870] Make KAHM only set custom values

- objectscale-graphql/templates/objectscale-admin-cluster-role.yaml
To create the registry secret in end-user namespaces, the API client
must have permissions to create secrets.
[OBSDEF-8171](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8171)
Docker secret `vsphere-docker-secret` is created successfully in end user namespace.
> [OBSDEF-8171] GraphQL needs secret create perms

- objectscale-portal/templates/objectscale-portal-deployment.yaml
- objectscale-portal/values.yaml
[OBSDEF-9082](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9082)
Updated the rsyslog configurations on objectscale-portal
> [OBSDEF-9082]-Fix for the defect OBSDEF-9082 - Replicasets not coming in Ready state intermittantly

- ecs-cluster/templates/fabric-proxy-api-token.yaml
- ecs-cluster/templates/fabric-proxy-rbac.yaml
Installing an objectstore in an enduser namespace breaks fabric proxy
because it does not have the permissions to get/list pods. We do not
want to enabled the permissions on the default service account (the
default sa attached to init containers), so we need to create our own.
Init containers cannot have separate serviceaccounts than the host Pod,
but we can create a custom API token and mount it as one in the init
container. This lets us keep a separation of privilege between the init
container and other Pod containers.
[OBSDEF-8172](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8172)
Related operator PR: https://eos2git.cec.lab.emc.com/ECS/ecs-flex-operator/pull/431
*Testing is ongoing for end user namespace to confirm this is all that …
> [OBSDEF-8172] Add fabric proxy rbac for enduser namespaces

- objectscale-dcm/templates/deployment.yaml
- objectscale-dcm/templates/encryption-key.yaml
[OBSDEF-9175](https://jira.cec.lab.emc.com/browse/OBSDEF-9175)
_add secret key generation for dcm_
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/194/
Tests output:
```
[root@localhost:~/0.71.2/charts(bugfix-OBSDEF-9175-dcm-enc-keys)]$ make test
helm version
version.BuildInfo{Version:"v3.6+unreleased", GitCommit:"3e1da5f39c512407ec64015437cfd1d3ece626c6", GitTreeState:"clean", GoVersion:"go1.14.2"}
yamllint --version
yamllint 1.20.0
helm lint common-lib ecs-cluster objectscale-manager mongoose zookeeper-operator atlas-operator decks kahm dks-testapp fio-test sonobuoy dellemc-license service-pod helm-controller objectscale-graphql …
```
> [OBSDEF-9175] dcm encryption key

- objectscale-dcm/templates/atlas_v1beta1_dcmcluster.yaml
- objectscale-dcm/values.yaml
[OBSDEF-9302](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9302)
Set DCM Atlas replicas to 3 (fixed value)
Set DCM Atlas disk to 3Gi for remote possibility of raft (consensus protocal) wal (write ahead logs) rotation.
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/198/
<pre><font color="#D3D7CF"><b>objectscale-dcm-7d86bdccb-gxjhj                    1/1     Running             0          78s</b></font>
<font color="#D3D7CF"><b>objectscale-dcm-atlas-0                            1/1     Running             0          57s</b></font>
<font color="#D3D7CF"><b>objectscale-dcm-atlas-1                            1/1     Running             0 …
> [OBSDEF-9302] set fixed dcm atlas replicas and disk resources for raft wal rotation

- ecs-cluster/templates/objectstore-rbac.yaml
[OBSDEF-8062] Fabric-proxy running in storagesrver pod needs list, get and watch CSI Bare-Metal volume CRDs to get actual volume health information (in order to provide it to its clients through Fabric Disk REST API)
> [OBSDEF-8062] Add storageserver service account rights to access CSI Bare-Metal volume CRDs

- kahm/templates/postgress-secrets.yaml
KAHM can disable the local postgres instance and can connect to the centralized postgres database. In order to connect to the remote instance, KAHM needs username, password, dbname, ip and port of the remote postgres db.
There was a bug where hostname wasn't setting properly. 
[OBSDEF-9326](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9326)
- [ x] make test passed
- [ x] make build passed
- [x ] helm install <chart> passed
> [OBSDEF-9326] allow KAHM to connect to remote postgres instance in case of the Atlantic platform 

- Makefile
- objectscale-manager/objectscale-manager-custom-values.yaml
- objectscale-manager/templates/objectscale-manager-app.yaml
```
objectscale-manager-alerts-84896c89df-k25d4                       4/4     Running          0          17m
objectscale-manager-bookkeeper-operator-78679c5d6b-ft5n9          2/2     Running          0          17m
objectscale-manager-fluxd-7dd95687f4-swsj7                        3/3     Running          0          17m
objectscale-manager-grafana-698f6c77c7-m8rlv                      5/5     Running          0          17m
objectscale-manager-influxdb-0                                    5/5     Running          0          16m
objectscale-manager-influxdb-1                                    5/5     Running          0          16m …
```
> [OBSDEF-9141] Make objectscale-manager upgradeable

- federation/templates/atlas_v1beta1_fedcluster.yaml
- federation/values.yaml
- objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
- objectscale-iam/values.yaml
[OBSDEF-9411](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9411)
- Added limits and requests memory for IAM and FEDSVC Atlas pods
Manual Testing 
```
0:~/EMCECS/charts # k describe po federation-atlas-0 | grep Limits -A3
Limits:
memory:  1000Mi
Requests:
memory:   256Mi
10:~/EMCECS/charts # 
10:~/EMCECS/charts # k describe po objectscale-iam-atlas-0 | grep Limits -A3
Limits:
memory:  1000Mi
Requests:
memory:   256Mi
```
> [OBSDEF-9411]Added limits and requests memory for IAM and FEDSVC Atlas pods

- .gitignore
- Makefile
- logging-injector/logging-injector-custom-values.yaml
- logging-injector/templates/logging-injector-app.yaml
- logging-injector/values.yaml
Make the vmware logging-injector yaml file only contain the specified
--set values, so upgrades will automatically update default values and
retain specific ones from customvalues.
- [] helm install <chart> passed
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/212/
> [OBSDEF-9143] Make logging injector upgradeable

- tools/issues_events_report/issues_events_reporter.py
https://jira.cec.lab.emc.com/browse/OBSDEF-9512
- [y] make test passed
- [y] make build passed
- [y] make release passed
Manual testing that `make generate-issues-events-all` works after `make build`.
> [OBSDEF-9512] Fix for generate-issues-events-all script to ignore rules without label

- objectscale-portal/templates/objectscale-portal-configmap.yaml
[OBSDEF-9622](https://jira.cec.lab.emc.com/browse/OBSDEF-9622)
Fixed path for token validation from `validate` to `validateToken`.
> [OBSDEF-9622] grafana: fix path for token validation

- objectscale-manager/templates/operator-rbac.yaml
It's needed to get storageType parameter when using Baremetal CSI
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/237/
> [OBSDEF-9595] Allow Operator read StorageClass resources

- Jenkinsfile
- snmp-notifier/Chart.yaml
- snmp-notifier/values.yaml
Update to PR Validation after ECS/infra-devkit/pull/43
The same fix as in ECS/pipelines/pull/956/
Also, updated values.yaml for snmp-notifier to meet values.schema.json to pass `make test`
> [FABRIC-9269] fix PR validation for charts

- kahm/templates/badgerdb-pvc.yaml
- kahm/templates/kahm.yaml
[OBSDEF9519n](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9519)
Don't mount PVC volume to the KAHM pod if the underlying DB is Postgres.
- [ x] make test passed
- [x ] make build passed
- [x ] helm install <chart> passed
- [ x] vSphere7 make package deployments passed
- [x ] helm upgrade <chart> passed
```
vinod@ubuntu:~/go/src/dellcharts/charts$ helm install kahm ./kahm --set db.dbType=BadgerDB --set db.postgres.enable=false -n vinod
NAME: kahm
LAST DEPLOYED: Thu Jul  1 15:34:54 2021
NAMESPACE: vinod
STATUS: deployed
REVISION: 1
NOTES:
Thank you for installing kahm. This release is capable of
deploying and upgrading Kubernetes Application Health Managements.
Your release is named kahm.
To install KAHM by using Helm chart, use the helm install command below:
$ helm install <repository …
```
> [OBSDEF-9519] removed badgerdb PVC when the database is postgres

- scripts/objectscale-install-main.sh
[OBSDEF-9694](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9694)
- Changed all `helm` calls to use the `--devel` option
- - this allows us to get the latest pre-release version `0.77.0-1172` 
```
./temp_package/openshift/objectscale-install.sh --set type=install  --set helmrepo=objs --set primaryStorageClassName=csi-baremetal-sc-ssdlvg   --set secondaryStorageClassName=csi-baremetal-sc-hddlvg --set global.registry=asdrepo.isus.emc.com:8099
└─ $ ▶  kubectl get pod
helmNAME                                                              READY   STATUS    RESTARTS   AGE
atlas-operator-9b7496457-8chnt                                    2/2     Running   0          19h
csi-baremetal-controller-cc86d5b99-cj654                          4/4     Running   0          21h
csi-baremetal-node-2kwpn …
```
> OBSDEF-9694 - use helm --devel option to pick up latest latest prerelease versions

- scripts/objectscale-install-main.sh
[OBSDEF-9984](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9984)
- properly create custom values for objectscale-manager 
```
./temp_package/openshift/objectscale-install.sh --set type=install  --set helmrepo=objs --set primaryStorageClassName=csi-baremetal-sc-hddlvg   --set secondaryStorageClassName=csi-baremetal-sc-hddlvg --set global.registry=asdrepo.isus.emc.com:8099
21.07.08 10:14:03 : ==============================================
21.07.08 10:14:03 : ObjectScale install version: 0.76.0
21.07.08 10:14:03 : ==============================================
21.07.08 10:14:03 : Locating kubectl...
21.07.08 10:14:03 : Client Version: v1.16.4
Server Version: v1.19.0+e405995
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", …
```
> OBSDEF-9984 - openshift install fix creating customvalues for objs-mgr

- objectscale-manager/crds/dellemc.com_serviceprocedures_crd.yaml
[OBSDEF-9941](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9941)
Cosmetic changes to show ServiceProcedures status and updated CRD's field according to current Go model.
Manual testing:
```
$ kubectl get serviceprocedure
NAME                                                    STATUS     AGE
disk-replacement-818d7b26-a1f4-4eed-a4c2-06ff449c079c   Rejected   7m5s
disk-replacement-c6fc1092-789c-4202-9ca0-67a83cf23de7   Rejected   2m41s
```
> [OBSDEF-9941] Add status field for ServiceProcedure CRD

- Makefile
- kahm/templates/rbac.yaml
- objectscale-manager/templates/operator-rbac.yaml
[OBSDEF-9481](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9481)
- for kahm healtchecks/CloudIQ set configmaps/finalizers
- for service procedure services set pods/finalizers & deployments/finalizers
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/255/
```
─ $ ▶  kubectl get svc
NAME                                     TYPE           CLUSTER-IP       EXTERNAL-IP                            PORT(S)             AGE
fedsvc                                   ClusterIP      172.30.103.149   <none>                                 9500/TCP            25s
kahm-postgresql-ha-pgpool                ClusterIP      172.30.213.100   <none>                                 5432/TCP            41s
kahm-postgresql-ha-postgresql            ClusterIP      172.30.14.83 …
```
> OBSDEF-9481 - set finalizers in OpenShift for configmaps, pods and deployments

- ecs-cluster/templates/ecs-cluster.yaml
- ecs-cluster/values.yaml
[OBSDEF-9484](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9484)
Add support of pravega and zookeeper pod affinity
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/254/
The pravega pod affinity has been configured via paremeters as expected, with required pod anti-affinity as default
> [OBSDEF-9484] Add support of pravega and zookeeper pod affinity

- Makefile
https://jira.cec.lab.emc.com/browse/OBSDEF-10108
Added ` || exit $?` for the `helm dep up` and `helm package` commands
Now errors should not be ignored
```
Updating package for logging-injector
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bereza/.kube/config
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://asdrepo.isus.emc.com/artifactory/objectscale-helm-build/" chart repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ecs2" chart repository
...Successfully got an update from the "ecs" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: can't get a valid version for repositories logging-injector. Try changing the version …
```
> [OBSDEF-10108] Exit if build or update dep failed

- objectscale-graphql/templates/objectscale-admin-cluster-role.yaml
Signed-off-by: Youmin_Han <Youmin_Han@dell.com>
[OBSDEF-10025](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-10025)
Missing clusterRole for listing pods in graphql
```
Charts:      29 passed, 29 total
Test Suites: 49 passed, 49 total
Tests:       238 passed, 238 total
Snapshot:    0 passed, 0 total
Time:        22.542549726s
```
> [OBSDEF-10025] Fix the cluster role for graphql

- ecs-cluster/templates/ecs-cluster.yaml
[OBSDEF-8800](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8800)
When excluding a node during ObjectStore Creation, would run into an issue where the helm value for .name could not be found. Changed {{ .name }} to {{ . }} as per https://helm.sh/docs/chart_template_guide/control_structures/#looping-with-the-range-action to resolve.
> [OBSDEF-8800] Stuck Suspending when Excluding Node in ObjectStore Creation

- decks/templates/decks.yaml
- kahm/templates/kahm.yaml
- supportassist/templates/supportassist.yaml
The app.kubernetes.io/instance labels **must** be set on all deployments and statefulsets so we can aggregate the application's readiness properly.
> [OBSDEF-9636] Add right resource labels

- common-lib/templates/_sp_operator_labels.yaml
- ecs-cluster/templates/ecs-cluster.yaml
- objectscale-iam/values.yaml
[OBSDEF-10597](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-10597)
Replace `sp-integrated-depends-on-stateful` label for the sp operator with the new one to ignore TMM Post check for the pravega controller
Also fixed indentation in the iam values to pass `make test`
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/310/
Helm install dry-run
```
$helm install objstore ecs-cluster/ --dry-run
...
controllerPodLabels:
app.kubernetes.io/namespace: default
objectscale.dellemc.com/logging-inject: "true"
objectscale.dellemc.com/logging-release-name: "objstore"
objectscale.dellemc.com/sp-integrated: "true"
objectscale.dellemc.com/sp-integrated-ignore-checks: "TMM-PodsAreReadyPostCheck"
segmentStorePodLabels: …
```
> [OBSDEF-10597] Refactor SP operator ignore checks labels

- statefuldaemonset-operator/templates/role.yaml
[OBSDEF-10711](https://jira.cec.lab.emc.com/browse/OBSDEF-10711)
Same as https://github.com/EMCECS/charts/pull/966 but to `release-objectscale-1.0-beta3`.
https://asd-ecs-jenkins.isus.emc.com/job/monitoring-libs/job/objectscale-charts/job/feature-OBSDEF-10711-statefuldaemonset-operator-beta3/2/
> [OBSDEF-10711] statefuldaemonset-operator: add new roles

- service-pod/values.yaml
OBSDEF-5500 - assign a fixed memory limit to the service pod of 2Gi, which should reduce the chances that kubelet decides to kill the pod to reclaim memory on an oversubscribed node.
> OBSDEF-5500 - Assign a memory limit to the service-pod that matches the memory request val

- objectscale-portal/templates/objectscale-portal-configmap.yaml
[OBSDEF-12056](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-12056)
Introduced new API to return the version of current deployment.  This build would be shown on the Login Page and on the Openshift/Standalone Menu.
_After genearating package:_
> obsdef-12056 - Added API to fetch Build
